// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package oapi

import (
	"time"
)

// Defines values for LogAction.
const (
	Expire LogAction = "expire"
	Pause  LogAction = "pause"
	Reset  LogAction = "reset"
	Resume LogAction = "resume"
	Select LogAction = "select"
	Start  LogAction = "start"
)

// Valid indicates whether the value is a known member of the LogAction enum.
func (e LogAction) Valid() bool {
	switch e {
	case Expire:
		return true
	case Pause:
		return true
	case Reset:
		return true
	case Resume:
		return true
	case Select:
		return true
	case Start:
		return true
	default:
		return false
	}
}

// Defines values for PomodoroState.
const (
	LongBreak  PomodoroState = "long_break"
	ShortBreak PomodoroState = "short_break"
	Work       PomodoroState = "work"
)

// Valid indicates whether the value is a known member of the PomodoroState enum.
func (e PomodoroState) Valid() bool {
	switch e {
	case LongBreak:
		return true
	case ShortBreak:
		return true
	case Work:
		return true
	default:
		return false
	}
}

// CreateLogEntryRequest defines model for CreateLogEntryRequest.
type CreateLogEntryRequest struct {
	// Action Timer event action. 'new_note' is excluded — use POST /notes instead.
	Action LogAction `json:"action"`

	// Payload Optional action-specific data
	Payload *map[string]interface{} `json:"payload,omitempty"`

	// Session Pomodoro timer state
	Session PomodoroState `json:"session"`
}

// CreateNoteRequest defines model for CreateNoteRequest.
type CreateNoteRequest struct {
	Note string `json:"note"`

	// PomodoroState Pomodoro timer state
	PomodoroState PomodoroState `json:"pomodoro_state"`
}

// Error defines model for Error.
type Error struct {
	Code    *string `json:"code,omitempty"`
	Message string  `json:"message"`
}

// LogAction Timer event action. 'new_note' is excluded — use POST /notes instead.
type LogAction string

// LogEntry defines model for LogEntry.
type LogEntry struct {
	// Action Timer event action. 'new_note' is excluded — use POST /notes instead.
	Action LogAction `json:"action"`
	Id     int64     `json:"id"`

	// Payload Optional action-specific data
	Payload *map[string]interface{} `json:"payload,omitempty"`

	// Session Pomodoro timer state
	Session   PomodoroState `json:"session"`
	Timestamp time.Time     `json:"timestamp"`
}

// LogEntryList defines model for LogEntryList.
type LogEntryList struct {
	Entries *[]LogEntry `json:"entries,omitempty"`
	Total   *int        `json:"total,omitempty"`
}

// Note defines model for Note.
type Note struct {
	CreatedAt time.Time `json:"created_at"`
	Id        int64     `json:"id"`
	Note      string    `json:"note"`

	// PomodoroState Pomodoro timer state
	PomodoroState PomodoroState `json:"pomodoro_state"`
}

// NoteList defines model for NoteList.
type NoteList struct {
	Notes *[]Note `json:"notes,omitempty"`
	Total *int    `json:"total,omitempty"`
}

// PomodoroState Pomodoro timer state
type PomodoroState string

// ListLogEntriesParams defines parameters for ListLogEntries.
type ListLogEntriesParams struct {
	Action  *LogAction     `form:"action,omitempty" json:"action,omitempty"`
	Session *PomodoroState `form:"session,omitempty" json:"session,omitempty"`

	// From Filter entries from this timestamp (inclusive)
	From *time.Time `form:"from,omitempty" json:"from,omitempty"`

	// To Filter entries up to this timestamp (inclusive)
	To     *time.Time `form:"to,omitempty" json:"to,omitempty"`
	Limit  *int       `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int       `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListNotesParams defines parameters for ListNotes.
type ListNotesParams struct {
	PomodoroState *PomodoroState `form:"pomodoro_state,omitempty" json:"pomodoro_state,omitempty"`
	Limit         *int           `form:"limit,omitempty" json:"limit,omitempty"`
	Offset        *int           `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateLogEntryJSONRequestBody defines body for CreateLogEntry for application/json ContentType.
type CreateLogEntryJSONRequestBody = CreateLogEntryRequest

// CreateNoteJSONRequestBody defines body for CreateNote for application/json ContentType.
type CreateNoteJSONRequestBody = CreateNoteRequest
